name: CI

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rails_version: [6.1.0, 7.0.0, 7.1.0, 7.2.0, master]
        ruby_version: ['3.3', '3.2', '3.1', '3.0']
        exclude:
          - { ruby_version: '3.0', rails_version: master }

    steps:
    - uses: actions/checkout@v4

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: "${{ matrix.ruby_version }}"

    - name: Run test
      env:
        RAILS_VERSION: "${{ matrix.rails_version }}"
      run: |
        gem update --system
        bundle update
        cd spec/dummy; rake db:migrate db:test:prepare; cd ../..
        bundle exec rake

    - name: Upload coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: "coverage-ruby-${{ matrix.ruby_version }}-rails-${{ matrix.rails_version }}"
        path: coverage

    - name: Show coverage
      if: always()
      run: |
        cat coverage/coverage.txt
